INSERT INTO TRANSACTION (
  TRANSACTION_DATE,
  TRANSACTION_AMOUNT,
  PATIENT_ID,
  DOCTOR_ID
) VALUES(
  (SELECT APPOINTMENT_DATE FROM APPOINTMENT WHERE APPOINTMENT_ID = 26),
  (SELECT DOCTOR_PAYMENT FROM DOCTOR WHERE DOCTOR_ID = (SELECT DOCTOR_ID FROM APPOINTMENT WHERE APPOINTMENT_ID = 26)),
  (SELECT PATIENT_ID FROM APPOINTMENT WHERE APPOINTMENT_ID = 26),
  (SELECT DOCTOR_ID FROM APPOINTMENT WHERE APPOINTMENT_ID = 26)
);

SELECT
  DOCTOR_ID
FROM
  APPOINTMENT
WHERE
  APPOINTMENT_ID = 26;

SELECT
  *
FROM
  APPOINTMENT;

ALTER TABLE TRANSACTION RENAME COLUMN DOCTTOR_ID TO DOCTOR_ID;

SELECT
  *
FROM
  TRANSACTION;

SELECT
  *
FROM
  DOCTOR;

ALTER TABLE TRANSACTION
  ADD TRANSACTION_FOR VARCHAR(
    255
  ) DEFAULT 'Doctors fee' NOT NULL;

ALTER TABLE TRANSACTION DROP column TRANSACTION_FOR;

SELECT
  *
FROM
  TRANSACTION;


alter table TRANSACTION
  add  PAYMENT_TO VARCHAR(255) DEFAULT 'Doctors/Shop' NOT NULL;


alter table DOCTOR 
drop column HOSPITAL_ID;

alter table APPOINTMENT
add HOSPITAL_ID NUMBER DEFAULT 3 NOT NULL;


SELECT
  *
FROM
  APPOINTMENT;

ALTER TABLE PRESCRIPTION DROP COLUMN SURGERY;

alter table PRESCRIPTION add SURGERY VARCHAR(255) DEFAULT 'No';

ALTER TABLE APPOINTMENT
  ADD PRESCRIPTION_ID NUMBER;

UPDATE APPOINTMENT
SET
  APPOINTMENT_STATUS='Completed', PRESCRIPTION_ID= (SELECT PRESCRIPTION_ID FROM PRESCRIPTION WHERE APPOINTMENT_ID=26)
WHERE
  APPOINTMENT_ID=26;


  SELECT
  *
FROM
  PRESCRIPTION;