CREATE OR REPLACE TYPE ADDRESS_TYPE AS
  OBJECT(
    PATIENT_DISTRICT VARCHAR(255),
    PATIENT_AREA VARCHAR(255),
    PATIENT_ROADNUMBER VARCHAR(255)
  );
  ALTER TABLE PATIENT
    ADD PATIENT_ADDRESS ADDRESS_TYPE;



 --select all docctor view
CREATE OR REPLACE VIEW DOCTOR_VIEW AS
  SELECT
    DOCTOR_ID,
    DOCTOR_NAME,
    DOCTOR_IMAGE,
    DOCTOR_SPECIALITY,
    DOCTOR_PAYMENT
  FROM
    DOCTOR;

SELECT
  DOCTOR_ID,
  DOCTOR_NAME,
  DOCTOR_IMAGE,
  DOCTOR_SPECIALITY,
  DOCTOR_PAYMENT
FROM
  DOCTOR_VIEW;


  --------------UPCOMING APPOINTMENT VIEW----------------
CREATE OR REPLACE VIEW UPCOMING_APPOINTMENT_VIEW AS
  SELECT
    A.APPOINTMENT_ID,
    A.APPOINTMENT_DATE,
    A.APPOINTMENT_TIME,
    A.APPOINTMENT_STATUS,
    A.PATIENT_ID,
    A.DOCTOR_ID,
    D.DOCTOR_NAME,
    D.DOCTOR_SPECIALITY,
    H.HOSPITAL_NAME,
    D.DOCTOR_IMAGE
  FROM
    APPOINTMENT A,
    DOCTOR      D,
    PATIENT     P,
    HOSPITAL    H
  WHERE
    A.PATIENT_ID = P.PATIENT_ID
    AND A.DOCTOR_ID = D.DOCTOR_ID
    AND A.APPOINTMENT_STATUS='Pending'
    AND H.HOSPITAL_ID = A.HOSPITAL_ID;



    -----------------PREVIOUS APPOINTMENT VIEW----------------
CREATE OR REPLACE VIEW PREVIOUS_APPOINTMENT_VIEW AS
  SELECT
    A.APPOINTMENT_ID,
    A.APPOINTMENT_DATE,
    A.APPOINTMENT_TIME,
    A.APPOINTMENT_STATUS,
    A.PATIENT_ID,
    A.DOCTOR_ID,
    D.DOCTOR_NAME,
    D.DOCTOR_SPECIALITY,
    H.HOSPITAL_NAME,
    D.DOCTOR_IMAGE
  FROM
    APPOINTMENT A,
    DOCTOR      D,
    PATIENT     P,
    HOSPITAL    H
  WHERE
    A.PATIENT_ID = P.PATIENT_ID
    AND A.DOCTOR_ID = D.DOCTOR_ID
    AND A.APPOINTMENT_STATUS='Completed'
    AND H.HOSPITAL_ID = A.HOSPITAL_ID;